### ISSUE TITLE
Conda-forge package ?

### ISSUE THREAD

**Issue by Zeitsperre** [mcarans/pytest-loguru#2]
Hi again @mcarans.

I was wondering if you would be interested making pytest-loguru available on conda-forge ? I can craft the recipe very quickly and tag you as maintainer if that interests you. Maintenance is completely automated, so very little additional effort needed. Let me know!

**Comment by mcarans** [comment]
I'm not familiar with conda-forge. Is it possible to upload from Linux? Would the recipe be in GitHub Actions?

**Comment by Zeitsperre** [comment]
The process is entirely Azure CI-based, and the recipe outlines can be found here: https://github.com/conda-forge/staged-recipes#faq.

Once the recipe PR is merged, a new repo will be created with you as a maintainer. When new versions are published on PyPI, automation will open a PR to update the recipe based on the new version available. No manual package uploading necessary.

Putting together a recipe for pytest-loguru would be very fast/easy. If this interests you, I can draft something up.

**Comment by mcarans** [comment]
OK sure, please go ahead.

**Comment by Zeitsperre** [comment]
See: https://github.com/conda-forge/staged-recipes/pull/18673

**Comment by mcarans** [comment]
@Zeitsperre Thanks for the PR and conda recipe. Please let me know all is good and then I'l lclose this issue (or you can).

**Comment by Zeitsperre** [comment]
Everything is good to be closed. Thanks again!
